# Generated by Django 2.1.5 on 2019-02-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

# Added birth_date and favorite_color to User model.
    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(null=True, verbose_name='User Birth Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_color',
            field=models.TextField(null=True, verbose_name='User Favorite Color'),
        ),
    ]
