# Generated by Django 2.1.5 on 2019-03-09 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='category name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='modified date')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], db_index=True, default='A', verbose_name='product active status')),
                ('name', models.TextField(verbose_name='product name')),
                ('description', models.TextField(null=True, verbose_name='product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='product price')),
                ('quantity', models.IntegerField(null=True, verbose_name='current stock quantity')),
                ('reorder_trigger', models.IntegerField()),
                ('reorder_quantity', models.IntegerField(null=True, verbose_name='stock replenishment quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='product category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(verbose_name='product image filename')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name="image's product")),
            ],
        ),
    ]
